const mongoose = require("mongoose");

const ficheSchema = mongoose.Schema({
    nom_enfant: { type: String, required: true },
    prenom_enfant: { type: String, required: true },
    adresse_enfant: { type: String, required: true },
    ddn_enfant: { type: String, required: true},
    numero_registre_enfant: { type: String, required: true },
    facebook_autorisation: { type: Boolean, required: true },
    nom_resp_1: { type: String, required: true },
    adresse_resp_1: { type: String, required: true },
    tel_resp_1: { type: Number, required: true },
    email_resp_1: { type: String, required: true },
    nom_resp_2: { type: String, required: false },
    adresse_resp_2: { type: String, required: false },
    tel_resp_2: { type: Number, required: false },
    email_resp_2: { type: String, required: false },
    tel_urgence: { type: Number, required: true },
    tetanos: { type: Date, required: true },
    groupe_sanguin: { type: String, required: true },
    protection_nuit: { type: Boolean, required: true },
    peur_nuit: { type: Boolean, required: true },
    appareil_dentaire: { type: Boolean, required: true },
    appareil_auditif: { type: Boolean, required: true },
    diabete: { type: Boolean, required: true },
    maladie_cardiaque: { type: Boolean, required: true },
    affection_peau: { type: Boolean, required: true },
    somnambulisme: { type: Boolean, required: true },
    insomnie: { type: Boolean, required: true }, 
    incontinence: { type: Boolean, required: true },
    eczema: { type: Boolean, required: true },
    asthme: { type: Boolean, required: true },
    sinusite: { type: Boolean, required: true },
    bronchite: { type: Boolean, required: true },
    saignement_nez: { type: Boolean, required: true },
    maux_tete: { type: Boolean, required: true },
    maux_ventre: { type: Boolean, required: true },
    constipation: { type: Boolean, required: true },
    diarrhee: { type: Boolean, required: true },
    vomissements: { type: Boolean, required: true },
    mal_route: { type: Boolean, required: true },
    acariens: { type: Boolean, required: true },
    pollen: { type: Boolean, required: true },
    soleil: { type: Boolean, required: true },
    maquillage: { type: Boolean, required: true },
    savon: { type: Boolean, required: true },
    poils_animaux: { type: Boolean, required: true },
    allergie_supplementaire: { type: String, required: true },
    sais_nager: { type: String, required: true },
    sport_difficile: { type: String, required: true },
    remarque_supplementaire: { type: String, required: true }
  });


module.exports = mongoose.model('Fiches', ficheSchema);